// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO2FzCn9qqwEFBWOp1bknHNQIKHnhWbiU',
    appId: '1:731797300633:web:9d05ce4754108460239f08',
    messagingSenderId: '731797300633',
    projectId: 'nossagenda-77df4',
    authDomain: 'nossagenda-77df4.firebaseapp.com',
    storageBucket: 'nossagenda-77df4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXZ_9TNacLHDe1csatYfRNxqwRST7OG8',
    appId: '1:731797300633:android:e1da1a4389031569239f08',
    messagingSenderId: '731797300633',
    projectId: 'nossagenda-77df4',
    storageBucket: 'nossagenda-77df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNs24glFFDiy7heEZskudfal03FlA_78',
    appId: '1:731797300633:ios:384da025974d0e94239f08',
    messagingSenderId: '731797300633',
    projectId: 'nossagenda-77df4',
    storageBucket: 'nossagenda-77df4.firebasestorage.app',
    iosBundleId: 'com.ronnilson.nossaDespesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNs24glFFDiy7heEZskudfal03FlA_78',
    appId: '1:731797300633:ios:384da025974d0e94239f08',
    messagingSenderId: '731797300633',
    projectId: 'nossagenda-77df4',
    storageBucket: 'nossagenda-77df4.firebasestorage.app',
    iosBundleId: 'com.ronnilson.nossaDespesas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO2FzCn9qqwEFBWOp1bknHNQIKHnhWbiU',
    appId: '1:731797300633:web:5a97f5190f0f23ac239f08',
    messagingSenderId: '731797300633',
    projectId: 'nossagenda-77df4',
    authDomain: 'nossagenda-77df4.firebaseapp.com',
    storageBucket: 'nossagenda-77df4.firebasestorage.app',
  );

}